# Appendix A References
<p>R. A. Becker, J. M. Chambers and A. R. Wilks (1988) <em>The New S Language. A Programming Environment for Data Analysis and Graphics.</em> Wadsworth &amp; Brooks/Cole.</p>
<p>J. Bowman, S. Emberson and M. Darnovsky (1996) <em>The Practical SQL Handbook. Using Structured Query Language.</em> Addison-Wesley.</p>
<p>J. M. Chambers (1998) <em>Programming with Data. A Guide to the S Language.</em> Springer-Verlag.</p>
<p>P. Dubois (2000) <em>MySQL.</em> New Riders.</p>
<p>M. Henning and S. Vinoski (1999) <em>Advanced CORBA Programming with C++.</em> Addison-Wesley.</p>
<p>K. Kline and D. Kline (2001) <em>SQL in a Nutshell.</em> O’Reilly.</p>
<p>B. Momjian (2000) <em>PostgreSQL: Introduction and Concepts.</em> Addison-Wesley. Also available at <a href="http://momjian.us/main/writings/pgsql/aw_pgsql_book/" class="uri">http://momjian.us/main/writings/pgsql/aw_pgsql_book/</a>.</p>
<p>B. D. Ripley (2001) Connections. <em>R News</em>, <strong>1/1</strong>, 16–7. <a href="https://www.r-project.org/doc/Rnews/Rnews_2001-1.pdf" class="uri">https://www.r-project.org/doc/Rnews/Rnews_2001-1.pdf</a></p>
<p>T. M. Therneau and P. M. Grambsch (2000) <em>Modeling Survival Data. Extending the Cox Model.</em> Springer-Verlag.</p>
<p>E. J. Yarger, G. Reese and T. King (1999) <em>MySQL &amp; mSQL</em>. O’Reilly.</p>
<hr />
<p><a href="" id="Function-and-variable-index"></a> <a href="" id="Function-and-variable-index-1"></a></p>

