--- 
title: "R Data Import/Export"
author: "R Development Core Team"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
output: bookdown::gitbook
documentclass: book
link-citations: yes
github-repo: ColinFay/r-data-import-export
description: "R Data Import/Export describes the import and export facilities available either in R itself or via packages which are available from CRAN.	"
---

# R Data Import/Export {-}
<p>This is a guide to importing and exporting data to and from R.</p>
<p>This manual is for R, version 3.4.2 (2017-09-28).</p>
<p>Copyright © 2000–2016 R Core Team</p>
<blockquote>
<p>Permission is granted to make and distribute verbatim copies of this manual provided the copyright notice and this permission notice are preserved on all copies.</p>
<p>Permission is granted to copy and distribute modified versions of this manual under the conditions for verbatim copying, provided that the entire resulting derived work is distributed under the terms of a permission notice identical to this one.</p>
<p>Permission is granted to copy and distribute translations of this manual into another language, under the above conditions for modified versions, except that this permission notice may be stated in a translation approved by the R Core Team.</p>
</blockquote>
<hr />
<p><a href="" id="Acknowledgements"></a> <a href="" id="Acknowledgements-1"></a></p>
# Acknowledgements {-}
<p>The relational databases part of this manual is based in part on an earlier manual by Douglas Bates and Saikat DebRoy. The principal author of this manual was Brian Ripley.</p>
<p>Many volunteers have contributed to the packages used here. The principal authors of the packages mentioned are</p>
<blockquote>
<table>
<tbody>
<tr class="odd">
<td align="left"><a href="https://CRAN.R-project.org/package=DBI"><strong>DBI</strong></a></td>
<td align="left">David A. James</td>
</tr>
<tr class="even">
<td align="left"><a href="https://CRAN.R-project.org/package=dataframes2xls"><strong>dataframes2xls</strong></a></td>
<td align="left">Guido van Steen</td>
</tr>
<tr class="odd">
<td align="left"><a href="https://CRAN.R-project.org/package=foreign"><strong>foreign</strong></a></td>
<td align="left">Thomas Lumley, Saikat DebRoy, Douglas Bates, Duncan Murdoch and Roger Bivand</td>
</tr>
<tr class="even">
<td align="left"><a href="https://CRAN.R-project.org/package=gdata"><strong>gdata</strong></a></td>
<td align="left">Gregory R. Warnes</td>
</tr>
<tr class="odd">
<td align="left"><a href="https://CRAN.R-project.org/package=ncdf4"><strong>ncdf4</strong></a></td>
<td align="left">David Pierce</td>
</tr>
<tr class="even">
<td align="left"><a href="https://CRAN.R-project.org/package=rJava"><strong>rJava</strong></a></td>
<td align="left">Simon Urbanek</td>
</tr>
<tr class="odd">
<td align="left"><a href="https://CRAN.R-project.org/package=RJDBC"><strong>RJDBC</strong></a></td>
<td align="left">Simon Urbanek</td>
</tr>
<tr class="even">
<td align="left"><a href="https://CRAN.R-project.org/package=RMySQL"><strong>RMySQL</strong></a></td>
<td align="left">David James and Saikat DebRoy</td>
</tr>
<tr class="odd">
<td align="left"><a href="https://CRAN.R-project.org/package=RNetCDF"><strong>RNetCDF</strong></a></td>
<td align="left">Pavel Michna</td>
</tr>
<tr class="even">
<td align="left"><a href="https://CRAN.R-project.org/package=RODBC"><strong>RODBC</strong></a></td>
<td align="left">Michael Lapsley and Brian Ripley</td>
</tr>
<tr class="odd">
<td align="left"><a href="https://CRAN.R-project.org/package=ROracle"><strong>ROracle</strong></a></td>
<td align="left">David A, James</td>
</tr>
<tr class="even">
<td align="left"><a href="https://CRAN.R-project.org/package=RPostgreSQL"><strong>RPostgreSQL</strong></a></td>
<td align="left">Sameer Kumar Prayaga and Tomoaki Nishiyama</td>
</tr>
<tr class="odd">
<td align="left"><strong>RSPerl</strong></td>
<td align="left">Duncan Temple Lang</td>
</tr>
<tr class="even">
<td align="left"><strong>RSPython</strong></td>
<td align="left">Duncan Temple Lang</td>
</tr>
<tr class="odd">
<td align="left"><a href="https://CRAN.R-project.org/package=RSQLite"><strong>RSQLite</strong></a></td>
<td align="left">David A, James</td>
</tr>
<tr class="even">
<td align="left"><strong>SJava</strong></td>
<td align="left">John Chambers and Duncan Temple Lang</td>
</tr>
<tr class="odd">
<td align="left"><a href="https://CRAN.R-project.org/package=WriteXLS"><strong>WriteXLS</strong></a></td>
<td align="left">Marc Schwartz</td>
</tr>
<tr class="even">
<td align="left"><a href="https://CRAN.R-project.org/package=XLConnect"><strong>XLConnect</strong></a></td>
<td align="left">Mirai Solutions GmbH</td>
</tr>
<tr class="odd">
<td align="left"><a href="https://CRAN.R-project.org/package=XML"><strong>XML</strong></a></td>
<td align="left">Duncan Temple Lang</td>
</tr>
</tbody>
</table>
</blockquote>
<p>Brian Ripley is the author of the support for connections.</p>
<hr />
<p><a href="" id="Introduction"></a> <a href="" id="Introduction-1"></a></p>
<div id="calibre_pb_4" class="calibre11">

</div>

